### ISSUE TITLE
Connect Supabase Account

### ISSUE THREAD

**Issue by jehrhardt** [jehrhardt/supapasskeys-app#35]
The user must be able to connect a Supabase account to Supapasskeys. There is an example for [building a marketplace integration](https://github.com/supabase/supabase/blob/master/examples/edge-functions/supabase/functions/connect-supabase/README.md).

An account in Supabase basically means to things:

- An user account
- An organization with one or multiple projects in it

Every organization can have multiple user accounts and all of them can login via oAuth 2 to Supapasskeys. Also every user account can belong to multiple organizations.

### Solution
We will mirror the concept of organizations and user accounts in the following way:

#### Organization
An organization is a mirror of the corresponding Supabase organization. It is initially created by the first user, who connects the organisation to Supapasskeys.

It is important that the Supabase organization's slug is stored as a reference to ensure the mirroring works.

#### User
An user account is a mirror of the corresponding Supabase user. It is initially created, when the user signs into Supapasskeys via oAuth 2. When user connects to another organization they belong to, a relation to the corresponding Supapasskeys organization is created.

The user account exists in Supabase Auth and can sign-in independently from oAuth 2.

### Todos

- [ ] Implement oAuth 2 for Supabase
- [ ] Create organization with slug
- [ ] Select organization in UI to show list of Supabase projects
- [ ] Connect another organization

**Comment by jehrhardt** [comment]
This project will be archived and the feature not be implemented.
