### ISSUE TITLE
Create Server for Supabase project

### ISSUE THREAD

**Issue by jehrhardt** [jehrhardt/supapasskeys-app#36]
For every connected Supabase project, a user must be able to create a Supapasskeys server as a Passkeys backend.

The Supapasskeys server lives in the API application.

### Non-goals
Not every user in an organization should be able to create and administrate servers. But a permission system will be implemented separately.

A project could potentially be linked to multiple servers in the future. But this is also not planned now.

### Solution
The API will provide the concept of a server. This server is a virtual server within Supapasskeys API. Servers in the API know nothing about Supabase itself. Instead the web application will establish and manage the connection.

#### API access
We will use the management API of the server implemented by jehrhardt/supapasskeys#45. We will store the signing key to generate a JWT as a secret in Supabase Vault.

#### Store project
A mirror of the Supabase project must be stored in the Supabase of the web application. It will hold the connection between Supabase and the server in the API. The following properties must be included:

- Project reference ID from Supabase
- Server ID from Supapasskeys API

If a project is deleted in Supabase, it will not be automatically deleted in Supapasskeys. But it will be shown as incative.

### Todos

- [ ] Create server via PostgREST
- [ ] Store project
- [ ] Show project as connected, if server is created
- [ ] Show project as disabled, if Supabase project has been deleted / disabled

**Comment by jehrhardt** [comment]
This project will be archived and the feature not be implemented.
